// Immediate suggestions; the full worldwide city list (~148k entries, from
// GeoNames via country-state-city, regenerated by scripts/gen-locations.mjs)
// is code-split and loaded on demand — see LocationInput.
export const WORK_ARRANGEMENTS = ['Remote', 'Remote (US)', 'Hybrid', 'On-site']

export const loadLocations = () =>
  import('./locations.data').then((m) => m.LOCATIONS)
