/**
 * Suggestions for the location field — work arrangements, every US state, and
 * the metros that show up most on job postings. It's a `<datalist>`, so typing
 * anything else (a scraped "Cupertino, CA", an international office) still works.
 */
export const US_LOCATIONS: string[] = [
  'Remote',
  'Remote (US)',
  'Hybrid',
  'On-site',
  // major metros — "City, ST"
  'San Francisco, CA',
  'San Jose, CA',
  'Los Angeles, CA',
  'San Diego, CA',
  'Sacramento, CA',
  'Seattle, WA',
  'Portland, OR',
  'New York, NY',
  'Brooklyn, NY',
  'Boston, MA',
  'Cambridge, MA',
  'Washington, DC',
  'Arlington, VA',
  'Austin, TX',
  'Dallas, TX',
  'Houston, TX',
  'San Antonio, TX',
  'Denver, CO',
  'Boulder, CO',
  'Chicago, IL',
  'Atlanta, GA',
  'Miami, FL',
  'Orlando, FL',
  'Tampa, FL',
  'Raleigh, NC',
  'Charlotte, NC',
  'Nashville, TN',
  'Philadelphia, PA',
  'Pittsburgh, PA',
  'Phoenix, AZ',
  'Salt Lake City, UT',
  'Minneapolis, MN',
  'Detroit, MI',
  'Columbus, OH',
  'Cleveland, OH',
  'Indianapolis, IN',
  'Kansas City, MO',
  'St. Louis, MO',
  'Las Vegas, NV',
  'Madison, WI',
  'Milwaukee, WI',
  'Baltimore, MD',
  'Pittsburgh, PA',
  'Newark, NJ',
  'Jersey City, NJ',
  'Providence, RI',
  'Richmond, VA',
  'New Orleans, LA',
  'Oklahoma City, OK',
  'Louisville, KY',
  'Memphis, TN',
  'Birmingham, AL',
  'Honolulu, HI',
  'Anchorage, AK',
  'Boise, ID',
  'Albuquerque, NM',
  'Omaha, NE',
  'Des Moines, IA',
  'Charleston, SC',
  'Hartford, CT',
  'Buffalo, NY',
  'Rochester, NY',
  // states (for postings that only say the state)
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
]
